version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/onsi/ginkgo
    versions:
    - 1.14.2
    - 1.15.0
    - 1.15.1
    - 1.15.2
    - 1.16.0
  - dependency-name: github.com/tidwall/gjson
    versions:
    - 1.6.7
    - 1.6.8
    - 1.7.1
    - 1.7.3
    - 1.7.4
  - dependency-name: github.com/golang/protobuf
    versions:
    - 1.4.3
    - 1.5.1
  - dependency-name: helm.sh/helm/v3
    versions:
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.4
    - 1.10.5
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/scripts"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
  - dependency-name: golang
    versions:
    - 1.15.7.pre.alpine
    - 1.15.8.pre.alpine
    - 1.16.0.pre.alpine
    - 1.16.1.pre.alpine
    - 1.16.2.pre.alpine
